SourceMau/SourceMau/SourceMau/Controllers/QuyenHanChucNangController.cs
using Common.Enum;
using Common.Utilities;
using Core.Interface.Service;
using Core.Model;
using SystemWebUI.Migrations;
using SystemWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SystemWebUI.Controllers
{
    public class QuyenHanChucNangController : Controller
    {
        private readonly IXuLyChucNang xlchucnang;
        public QuyenHanChucNangController(IXuLyChucNang xlchucnang)
        {
            this.xlchucnang = xlchucnang;
        }
        
        // GET: QuyenHanChucNang
        [ChildActionOnly]
        public PartialViewResult MenuQuyenHan()
        {
            List<MenuQuyenHanModel> menuModel = new List<MenuQuyenHanModel>();
            if (Session[ConstantValues.SessionKeyMenu] != null)
            {
                menuModel = new List<MenuQuyenHanModel>(SessionManager.ReturnSessionObject(ConstantValues.SessionKeyMenu) as List<MenuQuyenHanModel>);
            }
            else 
            {
                var user = SessionManager.ReturnSessionObject(ConstantValues.SessionKeyCurrentUser) as NguoiDung;
                if (user.DanhSachChucNang.Count() > 0)
                {
                    //var dsPhanQuyen = user.DanhSachChucNang;  
                    var dsChucNang = xlchucnang.DocDanhSachTatCaChucNangTuDanhSachId(user.DanhSachChucNang);
                    menuModel = MenuQuyenHanModel.SapXepMenu(dsChucNang);
                }
                SessionManager.RegisterSession(ConstantValues.SessionKeyMenu, menuModel);
            }
            
            return PartialView(menuModel);
        }
    }
}

SourceMau/SourceMau/SourceMau/Views/Shared/_Layout.cshtml
@using SystemWebUI.Migrations;
@using Core.Model
@using Common.Enum
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/Images/favicon.png">
    @Styles.Render("~/Content/chainstyle")
    <!--Reference the autogenerated SignalR hub script. -->

    @RenderSection("styles", false)
    <!--[if lt IE 9]>
        <script src="~/Content/backend/chainstyle/js/html5shiv.js"></script>
        <script src="~/Content/backend/chainstyle/js/respond.min.js"></script>
    <![endif]-->

    <script src="~/Content/backend/chainstyle/js/jquery-1.12.1.min.js"></script>
    <script src="~/Content/backend/chainstyle/js/jquery-ui-1.12.1.js"></script>
    <script src="~/Content/backend/chainstyle/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/backend/chainstyle/js/dataTables.bootstrap.js"></script>
    <script src="~/Content/backend/chainstyle/js/modernizr.min.js"></script>
    <script src="~/Content/backend/chainstyle/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/Content/backend/chainstyle/js/bootstrap.min.js"></script>
    <script src="~/Content/backend/chainstyle/js/jquery.cookies.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <script src="~/Content/Plugins/noty/jquery.noty.packaged.min.js"></script>
    <script src="~/Scripts/pages/notifications.js"></script>
    <script src="~/Scripts/bootstrap-toggle.min.js"></script>
    <link href="~/Content/backend/bootstrap-toggle.min.css" rel="stylesheet" />
    <link href="~/Content/backend/chainstyle/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="~/Content/backend/chainstyle/css/jquery-ui-1.12.1.css" rel="stylesheet"/>

    <link href="~/Content/Plugins/ionic/ionicons.min.css" rel="stylesheet"/>

    <script src="~/Content/backend/ckeditor/ckeditor.js"></script>
    <script src="~/Content/backend/ckeditor/adapters/jquery.js"></script>
    <script src="~/Content/backend/ckfinder/ckfinder.js"></script>
    <script src="~/Content/backend/utilities.js"></script>
    <script src="~/Content/backend/myFunc.js"></script>

    <!-- pagination -->
    <script src="~/Content/backend/chainstyle/js/jquery.twbsPagination.js"></script>
    <!-- end add pagination -->
    <style>
        .loading {
            position: fixed;
            height: 100%;
            width: 100%;
            top: 0;
            left: 0;
            z-index: 9999;
            background: rgba(0, 0, 0, 0.5);
            display: none;
        }

            .loading img {
                width: 100%;
            }

            .loading div {
                margin: 200px auto;
                width: 150px;
            }
        .control-label {
            text-align: right;
            margin-top: 8px;
        }
        .ckfinder .input-group-addon {
            position: relative;
            height: 30px;
            width: auto !important;
            display: inline-block;
            padding: 0;
        }
        .ckfinder .input-group-addon img {
            width: auto;
            height: 28px !important;
        }
        .ckfinder img.org {
            width: 0;
            height: auto !important;
            position: absolute;
            top: 0;
            right: -210px;
            opacity: 0;
            transition: all .5s;
            border: 1px solid #AAA;
            background: #CCC;
            padding: 2px;
            z-index: 10000;
        }
        .imgpreview {
            width: 200px !important;
            opacity: 1 !important;
        }
    </style>

</head>
<body>
    <header>
        <div class="headerwrapper">
            <div class="header-left">
                <a href="#" class="logo">
                    <img src="~/Images/logo-syt-hcm.png" width="30" />
                </a>
                <div class="pull-right">
                    <a href="#" class="menu-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>
            </div><!-- header-left -->

            <div class="header-right">

                <div class="pull-right">

                    <!--<form class="form form-search" action="">
                        <input type="search" class="form-control" placeholder="Tìm kiếm..."/>
                    </form>-->
                    <div class="btn-group btn-group-option">
                        <a href="/" style="color: white" class="btn btn-default"><i class="fa fa-home"></i></a>
                    </div>
                    <div class="btn-group btn-group-option">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="~/NguoiDung/ThongTinCaNhan"><i class="glyphicon glyphicon-user"></i> Thông tin cá nhân</a></li>
                            <li class="divider"></li>
                            <li><a href="~/Login/Logout"><i class="glyphicon glyphicon-log-out"></i> Đăng xuất</a></li>
                            @*<li>@Html.ActionLink("Đăng xuất", "Logout", "Manage", null, new { @class = "glyphicon glyphicon-log-out" })</li>*@
                        </ul>
                    </div><!-- btn-group -->

                </div><!-- pull-right -->

            </div><!-- header-right -->

        </div><!-- headerwrapper -->
    </header>
    <section>
        <div class="mainwrapper">
            <div class="leftpanel">
                <div class="media profile-left">
                    <a class="pull-left profile-thumb" href="~/NguoiDung/ThongTinCaNhan">
                        <img class="img-circle" src="~/Content/backend/chainstyle/images/photos/profile.png" alt="">
                    </a>
                    <div class="media-body">
                        @{ NguoiDung ng = SessionManager.ReturnSessionObject("CurrentUser") as NguoiDung;}
                        <h4 class="media-heading">@ng.Ten</h4>
                        @*<small class="text-muted">@ng.VaiTro.Ten</small>*@
                    </div>
                </div><!-- media -->

                <h5 class="leftpanel-title">Bảng điều khiển</h5>
                <ul class="nav nav-pills nav-stacked">
                    @{
                        Html.RenderAction("MenuQuyenHan", "QuyenHanChucNang");
                    }
                </ul>

            </div><!-- leftpanel -->

            <div class="mainpanel">
                @RenderBody()
                <div class="loading">
                    <div>
                        <img src="~/Images/loading_2.gif" />
                    </div>

                </div>
            </div>
        </div><!-- mainwrapper -->
    </section>
    @RenderSection("scripts", false)
    <script src="~/Content/backend/chainstyle/js/custom.js"></script>

</body>
</html>
@if (ViewBag.ThongBao != null)
{
    <script type="text/javascript">
            $(document).ready(function () {
                shownotify('@ViewBag.ThongBao.TypeNotify', '@ViewBag.ThongBao.Message');
            });
    </script>
}